import type { Product } from './types';

export const catalogProducts: Product[] = [
  {
    id: 'CAT-PROD-1001',
    name: 'Combine Harvester',
    description: 'A powerful combine harvester for all your harvesting needs.',
    price: 250000,
    images: ['/src/Assets/Combine.jpg', '/src/Assets/Harverster.jpg'],
    category: 'Harvesting Equipment',
    specs: {
      'Header Width': '7.5 meters',
      'Grain Tank': '10,000 Liters',
      'Engine Power': '350 HP',
      'Threshing System': 'Rotary Separator',
    },
  },
  {
    id: 'CAT-PROD-1002',
    name: 'Drone Sprayer',
    description: 'A high-tech drone sprayer for precision agriculture.',
    price: 15000,
    images: ['/src/Assets/Dronesprayer.png'],
    category: 'Precision Ag',
    specs: {
      'Tank Capacity': '10 Liters',
      'Flight Time': '15-20 minutes',
      'Spray Width': '4-6 meters',
      'Features': 'Obstacle Avoidance, RTK Positioning',
    },
  },
  {
    id: 'CAT-PROD-1003',
    name: 'Maize Sprinklers',
    description: 'Efficient sprinklers for maize fields.',
    price: 1200,
    images: ['/src/Assets/Maizesprinklers.png', '/src/Assets/Sprinklers.png', '/src/Assets/Sprinklers1.png'],
    category: 'Irrigation',
    specs: {
      'Coverage': '1 Acre',
      'Tubing Length': '500 meters',
      'Emitter Spacing': '30 cm',
      'Filter': '120-Mesh Disc Filter',
    },
  },
  {
    id: 'CAT-PROD-1004',
    name: 'New Tractor',
    description: 'A brand new tractor with the latest technology.',
    price: 75000,
    images: ['/src/Assets/Newtractor.png', '/src/Assets/Newtractor1.png', '/src/Assets/Newtractor2.png', '/src/Assets/Newtractor3.png', '/src/Assets/Newtractor4.png', '/src/Assets/Newtractor5.png', '/src/Assets/Newtractor6.png', '/src/Assets/Newtractor7.png', '/src/Assets/Newtractor8.png', '/src/Assets/Newtractor9.png', '/src/Assets/Newtractor10.png', '/src/Assets/Newtractor11.png'],
    category: 'Heavy Machinery',
    specs: {
      'Engine Power': '150 HP',
      'Transmission': '16-Speed PowerShift',
      'Lift Capacity': '5,000 kg',
      'GPS': 'Sub-inch Accuracy',
    },
  },
  {
    id: 'CAT-PROD-1005',
    name: 'Plough',
    description: 'A sturdy plough for all your tilling needs.',
    price: 45000,
    images: ['/src/Assets/Plough.png', '/src/Assets/Ploughs.png'],
    category: 'Planting Equipment',
    specs: {
      'Row Units': '8-Row',
      'Row Spacing': 'Adjustable (15-30 inches)',
      'Hopper Capacity': '50 Liters per row',
      'Control System': 'ISOBUS compatible',
    },
  },
  {
    id: 'CAT-PROD-1006',
    name: 'Rotavator',
    description: 'A powerful rotavator for preparing your soil.',
    price: 5000,
    images: ['/src/Assets/Rotavator-5-1.png'],
    category: 'Tillage Equipment',
    specs: {
        'Working Width': '1.5 meters',
        'Tine Type': 'L-type',
        'Tractor Power': '30-40 HP',
        'Weight': '250 kg',
    },
  },
  {
    id: 'CAT-PROD-1007',
    name: 'Tractor with Disc Harrow',
    description: 'A powerful tractor with a disc harrow for tilling.',
    price: 80000,
    images: ['/src/Assets/Tractorsdisc.jpg'],
    category: 'Tillage Equipment',
    specs: {
        'Tractor Power': '150 HP',
        'Harrow Width': '3 meters',
        'Number of Discs': '24',
        'Disc Diameter': '610 mm',
    },
  },
  {
    id: 'CAT-PROD-1008',
    name: 'Tractor Spraying',
    description: 'A tractor with a sprayer for all your spraying needs.',
    price: 85000,
    images: ['/src/Assets/Tractorsspraying.jpg.png'],
    category: 'Spraying Equipment',
    specs: {
        'Tractor Power': '150 HP',
        'Tank Capacity': '1000 Liters',
        'Boom Width': '12 meters',
        'Nozzle Type': 'Flat Fan',
    },
  },
  {
    id: 'CAT-PROD-1009',
    name: 'Seeder',
    description: 'A close-up of a seeder attached to a tractor.',
    price: 25000,
    images: ['/src/Assets/close-up-seeder-attached-tractor-field.jpg', '/src/Assets/new-red-agricultural-seeder-close-up-view-background-combine.jpg'],
    category: 'Planting Equipment',
    specs: {
        'Row Units': '12-Row',
        'Row Spacing': 'Adjustable (15-30 inches)',
        'Hopper Capacity': '70 Liters per row',
        'Control System': 'ISOBUS compatible',
    },
  },
];
